[package]
name = "resolved"
description = "Use DaVinci Resolve's Scripting API in Rust with Lua"
version = "0.2.0"
edition = "2024"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/VilleOlof/resolved"
repository = "https://github.com/VilleOlof/resolved"
authors = ["VilleOlof"]
keywords = ["davinci-resolve", "scripting-api", "lua", "studio"]
categories = ["api-bindings"]
rust-version = "1.89.0"

[workspace]
members = [
    "lua_module",
    "build_lib",
    "fudummy",
    "resolved_shared",
    "resolved_macros",
]
resolver = "3"

[workspace.dependencies]
resolved_shared = { version = "0.2.0", path = "./resolved_shared" }
rmpv = { version = "1.3", features = ["with-serde"] }
mlua = { version = "0.12", default-features = false }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3.0"
interprocess = "2.4.3"
rmp-serde = "1.3"
thiserror = "2"
tracing = "0.1"
itoa = "1"

[dependencies]
resolved_shared = { workspace = true }
rmp-serde = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
tokio = { version = "1.52", features = [
    "net",
    "fs",
    "macros",
    "process",
    "io-util",
    "sync",
    "time",
    "rt",
] }
resolved_macros = { version = "0.2.0", path = "resolved_macros", optional = true }
interprocess = { workspace = true, features = ["tokio"] }
tracing = { workspace = true, optional = true }
itoa = { workspace = true }
parking_lot = "0.12"
fastrand = "2.5"
futures = "0.3"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros", "time"] }
tracing-subscriber = { workspace = true }

[features]
default = ["pool", "macros"]
macros = ["dep:resolved_macros"]
tracing = ["dep:tracing"]
pool = []

[[bench]]
name = "simple"
harness = false

[profile.lua]
inherits = "release"
lto = true
codegen-units = 1

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []
