[package]
name = "fudummy"
description = "Dummy 'fuscript' binary to use for testing"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "../readme.md"
homepage = "https://github.com/VilleOlof/resolved"
repository = "https://github.com/VilleOlof/resolved"
authors = ["VilleOlof"]
publish = false

[dependencies]
mlua = { workspace = true, features = ["lua51"] }
