[package]
name = "lua_module"
description = "Prebuilt lua module included in 'resolve' that bridges the gap"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "../readme.md"
homepage = "https://github.com/VilleOlof/resolved"
repository = "https://github.com/VilleOlof/resolved"
authors = ["VilleOlof"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { workspace = true, features = ["lua51", "module", "serde"] }
resolved_shared = { workspace = true }
thiserror = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
rmpv = { version = "1.3.1", features = ["with-serde"] }
