[package]
name = "lua_module"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.12", features = [
    "lua51",
    "module",
    "serde",
], default-features = false }
resolved_shared = { workspace = true }
thiserror = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
tiny_http = "0.12"
