[package]
name = "lua_module"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { workspace = true, features = ["lua51", "module", "serde"] }
resolved_shared = { workspace = true }
thiserror = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }
rmpv = { version = "1.3.1", features = ["with-serde"] }
