[package]
name = "resolved_shared"
description = "Shared types between 'resolved' and it's internal lua module"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "../readme.md"
homepage = "https://github.com/VilleOlof/resolved"
repository = "https://github.com/VilleOlof/resolved"
authors = ["VilleOlof"]

[dependencies]
serde = { workspace = true }
shared_memory = "0.12.4"
interprocess = { version = "2.4.3", features = ["tokio"] }
thiserror = { workspace = true }
